<a href="https://colab.research.google.com/github/poonamkhot123/Numpy-practice/blob/main/Numpy_tutorial_ws_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

ARRAY


In [37]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [38]:
x = [1,2,3,4]
y = np.array([x])
print(y)
print(type(y))
print(y.ndim)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2


In [9]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [10]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [11]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [12]:
ar_zero = np.zeros((3,4))
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


 **Ones**


In [15]:
ar_one = np.ones(6)
print(ar_one)

[1. 1. 1. 1. 1. 1.]


**Empty**




In [16]:
ar_em = np.empty(4)
print(ar_em) # privious memory data 1 is printed here beacuse it takes that memory


[1. 1. 1. 1.]


**range**


In [17]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


**Diagonal**

In [18]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


**linespace**


In [23]:
ar_lin = np.linspace(1,20,num = 5)
print(ar_lin)

[ 1.    5.75 10.5  15.25 20.  ]


**Create numpy arrays with random numbers**

In [29]:
# rand():The function is used to generate random value between 0 to 1

var = np.random.rand(4)
print(var)

[0.21752237 0.38175723 0.03933325 0.78637701]


In [31]:
# randn(): the function is used to generate a random value close to zero.
# this may return positive or negative numbers as well.

var1 =np.random.randn(5)
print(var1)


[ 0.52985774  0.36377016  0.49937333 -0.36352268  0.71969432]


In [33]:
# ranf(): the function for doing random sampling in numpy.it returns an array of specified shape and fills it
# with random floats in the half_open interval. [0.0,1.0).

var2 = np.random.rand(5)
print(var2)


[0.19068748 0.82902895 0.65657322 0.98846973 0.5522059 ]


In [36]:
# randint() : the function is used to generate a random number between a given range.

var4 = np.random.randint(5,20,4)
print(var4)

# 5 is min value
# 20 max value
# 4 total number of values in output

[10 19  7 14]


**Data types**


In [38]:
var = np.array([1,2,3,4,12,12,14,15])
print("Data type : ",var.dtype)

Data type :  int64


In [11]:
var = np.array([1.0,1.2,1.3])
print("data type:", var.dtype)

data type: float64


In [12]:
var = np.array(["a","s","D","F"])
print("Data types:", var.dtype)

Data types: <U1


In [16]:
x = np.array([1,2,3,4],dtype = np.int32)
print("Data Type :",x.dtype)

Data Type : int32


 **Shape**

In [18]:
var = np.array([[1,2,3,4],[2,4,5,6]])
print(var)
print(var.shape)

[[1 2 3 4]
 [2 4 5 6]]
(2, 4)


In [25]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


**Reshape**


In [33]:
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)

print()
x = var2.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [40]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)

print()
x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
