<a href="https://colab.research.google.com/github/poonamkhot123/Numpy-practice/blob/main/numpy_practice_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # **Arithmetic operations**


In [ ]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varsub = var1 - var2
print(varsub)

[-1 -1 -1 -1]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varmul = var1 * var2
print(varmul)

[ 2  6 12 20]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
vardiv = var1 / var2
print(vardiv)

[0.5        0.66666667 0.75       0.8       ]


In [ ]:
print(np.add(4,5))

9


In [ ]:
var = np.array([1,2,3,4])
varadd = var % 3
print(varadd)

[1 2 0 1]


In [ ]:
# Reciprocal
var = np.array([1,2,30,20])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


# 2D Array


In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[2,3,4,5]])
varadd = var21+var22
print(varadd)

[[2 4 6 8]
 [3 5 7 9]]


In [ ]:
var21 = np.array([[1,2,3,4],[4,5,6,7]])
var22 = np.array([[2,3,4,5],[5,6,7,8]])
varmul = var21 * var22
print(varmul)

[[ 2  6 12 20]
 [20 30 42 56]]


# Arithmetic Functions

In [ ]:
# Basic Arithmetic Functions
# np.min(x)
# np.max(x)
# np.argmin(x) (finds position of min)
# np.argmax(x) (finds position of max)
# np.sqrt(x) ()
# np.sin(x)
# np.cos(x)
# np.cumsum(x) (community sum = first as it is add each one with privious)

In [ ]:
var = np.array([3,2,1,4,5,3,2])
print("min",np.min(var))
print("max",np.max(var))

min 1
max 5


In [ ]:
var = np.array([3,5,6,7,8,9])
print("min position",np.argmin(var))
print("max position",np.argmax(var))

min position 0
max position 5


In [ ]:
var1 =np.array([[2,7,3],[9,5,6]])
print(np.min(var1,axis =0))

[2 5 3]


In [ ]:
var1 = np.array([3,2,4,5,6,7])
print(np.sqrt(var1))

[1.73205081 1.41421356 2.         2.23606798 2.44948974 2.64575131]


In [ ]:
var1 = np.array([3,4,5,6,7])
print(np.sin(var1))
print(np.cos(var1))
print(np.cumsum(var1))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225]
[ 3  7 12 18 25]


# Broadcasting of Numpy array



In [ ]:
# same dimensions
# It helps do operations on arrays with different shapes without writing extra code or copying data.

In [ ]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()

(3,)

(3, 1)



In [ ]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()

print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing in Numpy Array
Indexing in NumPy means accessing individual elements of an array using their position (index).

In [ ]:
import numpy as np
var = np.array([9,8,7,6])
print(var[1]) # positive indexing at postion 1

8


In [ ]:
var = np.array([2,3,5,7,8])
print(var[-2]) # negative indexing for 1D array

7


In [ ]:
# indexing for 2D array
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])


[[9 8 7]
 [4 5 6]]
2

7


In [ ]:
#Indexing for 3D array
var2 = np.array([[[1,2],[6,9]]])
print(var2)
print()
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 9]]]

3

9


# Slicing in Numpy Array
Slicing means accessing a range of elements from an array using the start:stop:step format.

In [ ]:
# indexing of 1D array
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print("2 to 5:",var[1:5])
print("2 to end",var[1:])
print("start to 5:",var[:5])
print("stop:",var[1::2])

[1 2 3 4 5 6 7]

2 to 5: [2 3 4 5]
2 to end [2 3 4 5 6 7]
start to 5: [1 2 3 4 5]
stop: [2 4 6]


In [ ]:
# Indexing of 2D array
var1  = np.array([[1,2,3,4,5],[9,8,7,6,5],[13,14,15,16,17]])
print(var1)
print()
print(var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [13 14 15 16 17]]

[14 15 16 17]


# Iterating Numpy Array
Iterating means going through each element of a NumPy array one by one using loops (usually for loops).

In [ ]:
var = np.array([9,8,7,6,5,4])
for i in var:
  print(i)

9
8
7
6
5
4


In [ ]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()

for j in var:
  print(j)

# for iteration of values we have to use two times for loop.
for k in var:
  for l in k:
    print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]
1
2
3
4
1
2
3
4


In [ ]:
var3 = np.array([[[[9,8,7],[1,2,3]]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
  for j in i:
    for k in j:
        print(k)


[[[[9 8 7]
   [1 2 3]]]]
4

[9 8 7]
[1 2 3]


# nditer
np.nditer() is a universal iterator that lets you loop over every element in a NumPy array regardless of its dimensions, in a simple and efficient way.

# Why Use nditer?
Works for 1D, 2D, 3D, or higher dimensional arrays

Useful when you want to process each element one by one

Can be used with modification, index tracking, or simultaneous iteration



In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
  print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


# ndenumerate
np.ndenumerate() is a handy function in NumPy used to iterate through every element of an array along with its index (position) — even in multi-dimensional arrays.

In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d) # i stands for indexing value and d stands for data.

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# copy vs view

In [ ]:
var = np.array([1,2,3,4])
co = var.copy()
var[1]=40
print("var:",var)
print("copy:",co) # changes in original file not in copied file

var: [ 1 40  3  4]
copy: [1 2 3 4]


In [ ]:
x = np.array([9,8,6,5])
vi = x.view()
x[1]=40
print("x",x)
print("view:",vi) # changes in both original and copied both

x [ 9 40  6  5]
view: [ 9 40  6  5]


# join Array: joining means putting contents of two or more arrays in a single array.

In [ ]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [ ]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])
ar_new = np.concatenate((var,var1),axis = 0)
print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[1 2 3 4 9 8 7 6]


In [ ]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])
a_new = np.stack((var_1,var_2),axis = 1)
a_new1 = np.hstack((var_1,var_2)) # row
a_new2 = np.vstack((var_1,var_2)) # column
a_new3 = np.dstack((var_1,var_2)) #height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# split array


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,3)
print()
print(ar)
print(type(ar))

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [ ]:
var1 = np.array([[1,2],[4,3],[5,6]])
print(var)
ar1 = np.array_split(var1,3)
print()
print(ar1)

[1 2 3 4 5 6]

[array([[1, 2]]), array([[4, 3]]), array([[5, 6]])]


In [ ]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var)
ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis =1)
print()
print(ar1)
print()
print(ar2)

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# Search Array = Search an array for a certain value,and return the indexes that get a match.

In [ ]:
var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where( var == 2)
print(x)

(array([1, 4, 6]),)


In [ ]:
# Search Sorted Array = which performs a binary search in the array,and returns
# the index where the specified value would be inserted to maintain the search order.

In [ ]:
var1 = np.array([1,2,3,4,6,7,8,9,10])
# index          0,1,2,3,4,5,6
x1 = np.searchsorted(var1,5,side ="right")
print(x1)

4


# Sort array

In [ ]:
# sort array = Ordered sequence is any sequence that has an order
#corresponding to elements,like numeric or alphabetical,ascending or descending.

In [ ]:
# sorting of 1D array
var_1 =np.array([4,2,3,1,12,5,22,52,6,7])
print(np.sort(var1))

[1 2 3 4 6 7]


In [ ]:
# sorting of 1D array
var_2 = np.array(["a","s","d","f"])
print(np.sort(var_2))

['a' 'd' 'f' 's']


In [ ]:
# sorting of 2D array
var_1  = np.array([[4,3,2],[1,12,5],[22,52,6]])
print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [ ]:
# filter array = Getting some elements out
# of an existing array and creating a new array out of them.

# filter array

In [ ]:
var_3 = np.array(["a","s","d","f"])
f = [True,False,False,True]
new_a = var_3[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


# Arithmetic Functions

*Shuffle* – Mixes the rows or items in the array randomly.

*unique* – Finds and returns only the different (non-repeating) values in the array.

*resize* – Changes the size and shape of the array, and fills in extra space by repeating values if needed.

*flatten* – Makes a new 1D copy of the array, no matter how many dimensions it had.

*ravel* – Turns the array into 1D, like flatten, but tries not to make a new copy (faster and uses less memory).



In [ ]:
# Shuffle
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[1 5 4 2 3]


In [ ]:
# unique
var_1 = np.array([1,2,3,2,5,2,6,2,7])
x = np.unique(var1,return_index = True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 6, 7]), array([0, 1, 2, 3, 4, 5]), array([1, 1, 1, 1, 1, 1]))


In [ ]:
# resize
var2 = np.array([1,2,3,4,5,6])
y =np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#flatten,resize
var2 = np.resize(var2,(3,2))
print(y)
print()

print("Flatten:",y.flatten(order="F"))
print("Ravel:",np.ravel(y))


[[1 2]
 [3 4]
 [5 6]]

Flatten: [1 3 5 2 4 6]
Ravel: [1 2 3 4 5 6]


# Insert Function

In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print(var)
v= np.insert(var,2,40)
print(v)
# here insert into var
# at 2nd index number position
# value is 40

[1 2 3 4]
[ 1  2 40  3  4]


In [ ]:
# we can add same value at multiple index numbers
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,(2,4),40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [ ]:
# add one row
var = np.array([[1,2],[3,4]])
print(var)

v = np.insert(var,2,6,axis = 0)
print(v)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [6 6]]


In [ ]:
# append adding value at last of the array
var1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1,2,[22,23,24],axis = 0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


# Delete

In [ ]:
import numpy as np
var1 = np.array([1,2,3,4])
print(var1)
d = np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]


# Numpy Matrix

In [ ]:
var = np.matrix([[1,2,3],[2,6,8]])
print(var)
print(type(var))

[[1 2 3]
 [2 6 8]]
<class 'numpy.matrix'>


In [ ]:
var1 = np.array([[1,2,3],[2,3,5]])
print(var1)
print(type(var1))

[[1 2 3]
 [2 3 5]]
<class 'numpy.ndarray'>


In [ ]:
# addition of matrix
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[3,6]])
print(var)
print(type(var))
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[ 7 14]
 [ 7 14]]

[[ 7 14]
 [ 7 14]]


# Matrix function in numpy arrays
transpose() – Converts rows to columns, essential for reshaping and aligning matrix operations.

swapaxes() – Swaps two axes in multi-dimensional arrays for flexible axis manipulation.

inv() – Computes the inverse of a square matrix for solving linear systems.

matrix_power() – Raises a matrix to an integer power for repeated multiplication or transformations.

det() – Calculates the determinant to check matrix invertibility and solve equations.

In [ ]:
# Transpose #swapaxes
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))
print()

print(var.T)
print(np.transpose(var))

print()
print(var.T)

print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [ ]:
#inverse
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))




[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#power
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]



In [ ]:
#Determinanat
var5 = np.matrix([[13,12],[10,7]])
print(var5)
print()
print(np.linalg.det(var5))

[[13 12]
 [10  7]]

-29.000000000000018
